# Generated by Django 3.1.1 on 2020-09-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'portfolio', 'verbose_name_plural': 'portfolios'},
        ),
    ]
